#!/usr/bin/env zsh

date=$(date +"%b %d %Y")

workout_a() { 
    echo "Weight Used for Squat: "
    read squat

    echo "Weight Used for Bench Press: "
    read bench_press

    echo "Weight Used for Barbell Rows: "
    read rows

    echo "$date, A, $squat, $bench_press, -, $rows, -" >> workout.csv
    echo "Logged Workout A on $(date)"
}

workout_b() { 
    echo "Weight Used for Squat: "
    read squat

    echo "Weight Used for Overhead Press: "
    read overhead_press

    echo "Weight Used for Barbell Deadlift: "
    read deadlift 

    echo "$date, B, $squat, -, $overhead_press, -, $deadlift" >> workout.csv
    echo "Logged Workout B on $(date)"
}

create_file() {
    echo "workout.csv not found"
    echo "Creating a new file ..."
    echo "Date, Workout, Squat Weight (in Kg), Bench Press (in Kg), Overhead Press (in Kg), Barbell Rows (in Kg), Deadlift (in Kg)" > workout.csv
}

[ -e workout.csv ] || create_file

# Actual Script
case "$1" in 
    a|A) workout_a ;;
    b|B) workout_b ;;
    *) printf "Options\\n\\n a:\\tLog Workout A\\n b:\\tLog Workout B\\n" ;;
esac
